# Generated by Django 5.2 on 2025-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_description_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
