# Generated by Django 5.2 on 2025-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
