# Generated by Django 5.2 on 2025-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_sale_is_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
