# Generated by Django 6.0.5 on 2026-05-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_saleitem_is_voided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
